---

- name: Backup old rsyslog file
  shell: |
    mv /etc/logrotate.d/rsyslog /etc/logrotate.d/rsyslog.bk
  ignore_errors: true

- name: Configure log rotation
  blockinfile:
    path: /etc/logrotate.d/rsyslog
    create: true
    block: |
      /var/log/syslog
      {
          rotate 5
          maxsize 2G
          missingok
          notifempty
          delaycompress
          compress
          postrotate
              /usr/lib/rsyslog/rsyslog-rotate
          endscript
      }
      /var/log/mail.info
      /var/log/mail.warn
      /var/log/mail.err
      /var/log/daemon.log
      /var/log/kern.log
      /var/log/auth.log
      /var/log/user.log
      /var/log/lpr.log
      /var/log/cron.log
      /var/log/debug
      /var/log/messages
      {
          rotate 5
          daily
          maxsize 15G
          missingok
          notifempty
          compress
          delaycompress
          sharedscripts
          postrotate
              /usr/lib/rsyslog/rsyslog-rotate
          endscript
      }

- name: Delete old rsyslog file
  shell: |
    rm -f /etc/logrotate.d/rsyslog.bk
  ignore_errors: true