---
- name: download node_exporter
  get_url:
    url: 'https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
    dest: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
    mode: '0700'

- name: unarchive node_exporter
  unarchive:
    src: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
    remote_src: yes
    dest: '/tmp'

- name: copy node_exporter binary
  copy:
    src: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter'
    dest: '/usr/local/bin/'
    remote_src: true
    owner: root
    group: root
    mode: 755
    force: yes

- name: create node_exporter systemd unit
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0600'

- name: start node_exporter service
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false

- name: Add node exporter aliases
  blockinfile:
    marker_begin: "exporter_begin"
    marker_end: "exporter_end"
    path: '{{ user_dir }}/.bashrc'
    block: |
      alias nelog='journalctl -u node_exporter -f'
      alias nestart='sudo systemctl start node_exporter'
      alias nestop='sudo systemctl stop node_exporter'
      alias nestatus='sudo systemctl status node_exporter'
    state: present
